image: atlassian/default-image:2

pipelines:
  default:
    - step:
        script:
          - mkdir artifact
          - echo "Frontend Bitbucket Pipeline!" > artifact/index.html
        artifacts:
          - artifact/*
    - step:
        deployment: production
        script:
          - pipe: atlassian/aws-s3-deploy:0.3.7
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              S3_BUCKET: $S3_BUCKET
              EXPIRES: '2020-10-10'
              LOCAL_PATH: 'artifact'
              ACL: 'public-read'
