// File globals.ts
export const nav_logo = '/assets/images/nav-logo.svg'
export const logo = '/assets/images/auth-logo.svg'
export const icon_logo = '/assets/images/icon-logo.svg'
export const simplexam_logo = '/assets/images/logo.svg'
export const profile_bg = '/assets/images/profile.jpg'
export const xls = '/assets/images/xls.svg'
export const xls_1 = '/assets/images/xls_1.svg'
export const pdf = '/assets/images/pdf.svg'
export const profile = '/assets/images/profile.svg'
export const no_data = '/assets/images/no_data.svg'
export const notification_user = '/assets/images/user.jpg'
export const table_no_data = '/assets/images/no_data_avaliable.svg'
export const docx = '/assets/images/docx.svg'
export const csv = '/assets/images/csv.svg'
export const file = '/assets/images/file.svg'
export const completed = '/assets/images/success.svg'
export const incompleted = '/assets/images/incompeted.svg'
export const left_voicemail = '/assets/images/left_voice.svg'
export const page_not_found = '/assets/images/page_not_found.png'
export const switch_user = '/assets/images/switch-user.svg'
export const simplexam_service = '/assets/images/simplexam-service.svg'
export const default_select = '/assets/images/default-select.svg'
export const alert = '/assets/images/alert.svg'
export const info = '/assets/images/info.svg'
export const mp3 = '/assets/images/mp3.svg'
export const status_complete = '/assets/images/status-complete.svg'
export const status_inprogress = '/assets/images/status-inprogress.svg'
export const visa_card = '/assets/images/visa.svg'
export const amex_card = '/assets/images/amex.png'
export const cartes_bancaires_card = '/assets/images/cartes_bancaires.png'
export const diners_club_card = '/assets/images/diners_club.png'
export const discover_card = '/assets/images/discover.png'
export const jcb_card = '/assets/images/jcb.png'
export const mastercard_card = '/assets/images/mastercard.jpg'
export const unionpay_card = '/assets/images/unionpay.png'
export const error = '/assets/images/error.svg'


export const roles = [{}, {}]

